server:
  port: 8010
spring:
  data:
#    mongodb:
#      username: bankatidb
#      password: bankatidb
#      host: localhost
#      port: 27018
#      database: user
#      authentication-database: admin

application:
  config:
    virtualCard-url: http://localhost:8222/api/v1/virtualcard
    wallet-url: http://localhost:8222/api/v1/wallet
    walletcrypto-url: http://localhost:8222/api/v1/walletcrypto
    transactions-url: http://localhost:8222/api/v1/transactions
    servicestiers-url: http://localhost:8222/api/v1/servicestiers
    depense-url: http://localhost:8222/api/v1/depenses
