server:
  port: 8070
spring:
  data:
    mongodb:
      username: bankatidb
      password: bankatidb
      host: localhost
      port: 27018
      database: walletcrypto
      authentication-database: admin

application:
  config:
    users-url: http://localhost:8222/api/v1/users
    wallet-url: http://localhost:8222/api/v1/wallet
    transactions-url: http://localhost:8222/api/v1/transactions
    servicestiers-url: http://localhost:8222/api/v1/servicestiers
